name: HelloAction
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

env:
  name: Shima

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUBCONTEXT: ${{toJson(github) }}
        run: echo "$GITHUBCONTEXT"

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      name: Alireza
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Display PR information
        run: |
          echo Hello, $name!
          echo Actor: ${{ github.actor }}
          echo Committed By: ${{ github.event.commits[0].author.name }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, $name!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
