name: HelloAction
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

env:
  name: Shima

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUBCONTEXT: ${{toJson(github) }}
        run: echo "$GITHUBCONTEXT"

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      name: Alireza
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Display PR information
        if: github.event_name == 'push'
        run: |
          echo "Committer: ${{ github.actor }}"
          echo "Commit Author: ${{ github.event.head_commit.author.name }}"
          echo "Commit Author Email: ${{ github.event.head_commit.author.email }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, $name!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
