name: Example Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display information based on event type
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "This is a push event."
          echo "Committer: ${{ github.actor }}"
          echo "Commit Author: ${{ github.event.head_commit.author.name }}"
          echo "Commit Author Email: ${{ github.event.head_commit.author.email }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "This is a pull request event."
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"
        elif [ "${{ github.event_name }}" == "push" ] && [ -z "${{ github.event.before }}" ]; then
          echo "This is a commit-only event."
          # Add handling for commit-only events if needed
        else
          echo "Unsupported event type."
        fi
